language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - libstdc++-4.9-dev
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - zlib1g-dev
    - libcunit1-dev
    - libssl-dev
    - libxml2-dev
    - libev-dev
    - libevent-dev
    - libjansson-dev
    - libjemalloc-dev
before_install:
  - $CC --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CC --version
  - go version
before_script:
  # First build spdylay, since integration tests require it.
  # spdylay is going to be built under third-party/spdylay
  - cd third-party
  - git clone https://github.com/tatsuhiro-t/spdylay.git
  - cd spdylay
  - autoreconf -i
  - ./configure --disable-src --disable-examples
  - make check
  - export SPDYLAY_HOME=$PWD
  - cd ../..
  # Now build nghttp2
  - autoreconf -i
  - git submodule update --init
  - ./configure --enable-werror --with-mruby --with-neverbleed LIBSPDYLAY_CFLAGS="-I$SPDYLAY_HOME/lib/includes" LIBSPDYLAY_LIBS="-L$SPDYLAY_HOME/lib/.libs -lspdylay"
script:
  - make
  - make check
  - cd integration-tests
  - export GOPATH="$PWD/integration-tests/golang"
  - make itprep
  - make it
